AutoTrim, On

; SubString Wrapper for Lorem ipsum text
; Made for use with Appifyer (http://appifyer.com/)
; Author: Frankie Bagnardi
; Author Site: http://aboutscript.com/
; Tested on AutoHotkey_L 1.1.05.00 Unicode 32-bit
SubLorem(p*) {

	static
	static  FirstCall := true
	if FirstCall
	{
		; Source: http://www.loremipsum.de/downloads/version6.txt
		LoremText =
		(LTrim
         Hiss give me fish rip the couch jump on the table sleep in the sink, tail flick claw run chuf lay down in your way sniff. Lay down in your way chase the red dot leap climb the curtains, I don't like that food toss the mousie stretching purr puking sunbathe catnip rip the couch. Chuf toss the mousie toss the mousie chuf sleep in the sink sunbathe, sleep in the sink attack catnip meow. Climb the curtains hiss eat the grass feed me, rip the couch chase the red dot purr sleep in the sink feed me hiss climb the curtains. Lay down in your way toss the mousie lick lay down in your way, climb the curtains kittens kittens purr I don't like that food shed everywhere. Hairball feed me sleep on your keyboard I don't like that food, catnip tail flick chase the red dot zzz stretching give me fish. Chase the red dot scratched run purr kittens, scratched jump on the table meow toss the mousie lick.

         Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec bibendum nisi non sollicitudin vestibulum. Duis bibendum mauris nec diam congue egestas. Pellentesque massa neque, pharetra ac nibh quis, gravida hendrerit nibh. Curabitur vulputate, risus ut ultricies varius, leo elit aliquam nisl, ac aliquam nunc felis id sapien. Mauris lobortis tellus non eleifend dictum. Vestibulum ac elit ac nibh tristique tincidunt at a lectus. Nulla vel libero pharetra, cursus odio in, molestie arcu. Suspendisse potenti. Nunc tempor mi mollis, bibendum massa vel, pellentesque arcu. Mauris mollis pharetra orci, eget vehicula elit pellentesque ut. Pellentesque egestas tincidunt ligula, at lacinia neque commodo ac. Suspendisse quis dictum eros. Aenean dignissim leo mi, nec consectetur libero facilisis sed. Vestibulum aliquam risus ante, in maximus lacus tincidunt in. Praesent commodo sapien urna, vitae dapibus enim faucibus in.

         90's quinoa Neutra Tumblr, PBR cred sriracha. Stumptown sartorial vinyl four dollar toast cronut. Kogi Bushwick four dollar toast cornhole, blog fanny pack gluten-free skateboard bicycle rights paleo narwhal cronut farm-to-table viral mustache. Four dollar toast skateboard hashtag Godard Marfa, sartorial pop-up letterpress Bushwick DIY wolf locavore pour-over chia. Squid plaid retro, wayfarers Pinterest bitters Etsy. Austin plaid cliche street art chambray, migas craft beer small batch art party iPhone try-hard. Taxidermy craft beer blog selvage street art skateboard.                                                                                                                                    .. Proin sed lectus eu justo fringilla laoreet. Pellentesque pulvinar ut velit sit amet vulputate.

         It'll be flick mate gutful of fruit loop. Come a bradman piece of piss built like a pokies. Built like a jumbuck also as busy as a smoko. As cross as a garbo when stands out like a cobber. As busy as a ute no worries you little ripper top end. Grab us a dunny rat mate built like a hit the turps. It'll be bottle-o flamin built like a roo. We're going dipstick bloody coathanger. Grab us a bogged to come a grouse. Get a dog up ya gyno trent from punchy barbie.

         Bacon ipsum dolor amet venison sausage t-bone, shoulder tenderloin biltong corned beef pastrami leberkas salami pancetta tri-tip. Pork boudin ribeye cupim meatball. Shoulder kielbasa salami short ribs ribeye tenderloin filet mignon doner t-bone swine. Capicola shoulder t-bone prosciutto shank corned beef tri-tip beef ribs.

         Climb the curtains chase the red dot hiss attack your ankles chase the red dot lay down in your way, eat the grass climb the curtains zzz eat. Hairball purr eat the grass eat the grass hiss, tail flick puking sleep on your keyboard feed me judging you hiss. Give me fish sniff tail flick stuck in a tree tail flick, shed everywhere tail flick climb the curtains scratched sleep in the sink scratched. Sunbathe lay down in your way chase the red dot litter box, I don't like that food stretching sleep on your keyboard hairball rip the couch zzz. Stretching litter box sleep on your keyboard claw, attack lick lick fluffy fur jump on the table claw I don't like that food feed me. Tail flick sunbathe puking sleep in the sink climb the curtains, shed everywhere stuck in a tree run run eat biting. Judging you toss the mousie run shed everywhere sunbathe sleep on your face, meow eat climb the curtains tail flick attack your ankles.

         Praesent at feugiat ipsum. Donec eget nisi consequat, tincidunt diam sed, tincidunt leo. Suspendisse potenti. Aliquam aliquam tristique lorem eget finibus. Proin vel risus venenatis, molestie odio sit amet, venenatis dolor. Nulla eu urna ut turpis lobortis varius. Mauris pretium velit in enim efficitur, a varius risus venenatis. In hac habitasse platea dictumst. Pellentesque orci nibh, posuere et enim quis, bibendum tempor erat. Sed sit amet erat nibh. Integer facilisis sem ac lacinia interdum. Proin scelerisque lacus orci, nec consequat tortor porta et. Suspendisse sit amet lorem neque.

         Bespoke listicle dreamcatcher chia lumbersexual. Sartorial vinyl pug lo-fi lomo. Meditation Carles mixtape, Helvetica put a bird on it keffiyeh Pitchfork selvage fixie messenger bag ennui American Apparel. Pickled irony viral, ennui fanny pack Neutra iPhone distillery Williamsburg scenester authentic Tumblr aesthetic master cleanse. Actually Shoreditch tousled kale chips, pickled photo booth Schlitz. Tilde iPhone flexitarian, sustainable roof party blog High Life. McSweeney's disrupt church-key, fanny pack YOLO chambray organic polaroid pickled plaid migas.                                                                                                                                               Tail flick chuf eat purr meow stuck in a tree, meow tail

         Lets get some brumby heaps lets throw a strides. Lets throw a gobful flamin she'll be right dinky-di. Mad as a crack a fat where as cunning as a kindie. Come a bottlo bloody ciggies. Lets throw a prezzy flamin he hasn't got a greenie. pig's arse where lets get some budgie smugglers. He's got a massive joey my flat out like a cane toad. As dry as a sleepout also it'll be his blood's worth bottling. As cross as a aerial pingpong also flat out like a crook.

         Meatball jerky shoulder chicken boudin turducken leberkas, alcatra bresaola shankle landjaeger brisket pork chop ribeye cupim. Pastrami pork chop meatloaf, flank spare ribs cupim ground round prosciutto capicola sausage. Sirloin cow pancetta doner corned beef alcatra rump bresaola beef ham hock biltong. Drumstick rump ham tenderloin beef ribs short loin shoulder pig, cupim kevin boudin pork loin tail turducken sausage.

         Puking jump sleep in the sink catnip litter box, biting jump chase the red dot jump on the table bat purr. Jump jump tail flick jump on the table climb the curtains attack, chuf fluffy fur kittens bat. Stuck in a tree sleep on your keyboard tail flick sunbathe, meow chuf sleep on your face shed everywhere knock over the lamp feed me. Leap jump on the table leap attack attack puking, knock over the lamp scratched jump on the table stretching lay down in your way. Attack tail flick eat the grass rip the couch fluffy fur, jump on the table sleep on your keyboard jump on the table feed me lay down in your way litter box sleep in the sink. Stretching kittens jump on the table leap, give me fish puking leap fluffy fur sleep in the sink sleep on your keyboard litter box sleep on your keyboard. Lick lick jump scratched attack your ankles attack your ankles, purr attack toss the mousie I don't like that food.

         Sed quam sapien, convallis eget tempor vitae, cursus in nisl. Morbi quis convallis metus. In ultricies elementum velit, nec ornare leo scelerisque vitae. Nam efficitur est in odio gravida, in euismod elit mattis. Phasellus non aliquet risus. Sed ex odio, ornare vitae tellus quis, tincidunt ullamcorper lorem. Pellentesque gravida condimentum erat nec sodales. Duis a tincidunt magna. Phasellus in porttitor nunc. Curabitur luctus aliquam lorem non feugiat. Morbi vestibulum metus dui, at finibus augue auctor in. Etiam molestie fermentum nunc, ac pellentesque dui ultrices vitae. Sed venenatis ac eros non tempor. Proin sed lectus eu justo fringilla laoreet. Pellentesque pulvinar ut velit sit amet vulputate.

         Small batch Odd Future meh health goth bespoke. 8-bit cornhole kitsch semiotics, crucifix PBR&B cliche asymmetrical bitters keffiyeh. Leggings cardigan sartorial aesthetic pop-up synth. 8-bit mixtape freegan, mlkshk Vice Neutra ugh kale chips Austin VHS organic ethical pork belly. Banksy tilde literally, pork belly Helvetica yr lomo put a bird on it +1. Freegan retro quinoa Carles banjo. Cardigan Pinterest plaid, chia stumptown distillery crucifix shabby chic Godard ennui American Apparel tote bag disrupt semiotics meditation.

         Grab us a pash no dramas flat out like a struth. Stands out like a bingle piece of piss as busy as a buckley's chance. You little ripper jillaroo as cunning as a piker. Lets throw a dill mate lets throw a yakka. Lets get some vb my it'll be counter meal. He hasn't got a bathers my you little ripper damper. As stands out like bail up when as stands out like gobful. As dry as a crack a fat where we're going roo. She'll be right deadset flamin we're going throw-down. As dry as a true blue piece of piss shazza got us some pozzy. We're going slabs also lets get some dinky-di.

         Tenderloin pork loin alcatra, short ribs cupim flank turkey drumstick t-bone swine turducken rump tail. Landjaeger corned beef biltong pastrami, doner chuck fatback leberkas prosciutto bacon alcatra. Jerky beef turducken, tri-tip short ribs flank bacon kielbasa landjaeger cupim pork chop spare ribs ribeye chuck hamburger. Jerky strip steak meatloaf ball tip. Short loin hamburger pork loin chuck tri-tip pancetta ham hock pastrami kielbasa ground round alcatra ball tip strip steak.

         Tail flick chuf eat purr meow stuck in a tree, meow tail flick lick give me fish eat. Eat the grass purr toss the mousie litter box jump on the table sleep on your face, knock over the lamp bat eat the grass chase the red dot lay down in your way. Scratched knock over the lamp purr attack your ankles leap, zzz jump on the table zzz shed everywhere stretching chase the red dot judging you. Knock over the lamp litter box claw bat, I don't like that food scratched I don't like that food I don't like that food judging you chuf. Climb the curtains chuf sleep in the sink hairball, tail flick sleep on your face hairball stretching knock over the lamp sunbathe meow. Fluffy fur fluffy fur stuck in a tree chuf, jump on the table leap jump on the table zzz jump feed me leap. Jump on the table attack leap leap, attack your ankles scratched hairball toss the mousie hairball scratched. Leap tail flick toss the mousie hiss fluffy fur, stretching meow scratched purr toss the mousie.

         Vestibulum mollis tempor orci at varius. Vestibulum et justo vel est feugiat bibendum vitae eget nibh. Vestibulum laoreet sapien id odio interdum venenatis. Nunc sed nibh sit amet odio sodales sodales. Nulla efficitur varius ipsum ut pulvinar. Suspendisse potenti. Aliquam ut pharetra elit. Ut arcu orci, molestie a tellus sed, vehicula placerat erat. Quisque molestie velit sed neque fringilla, vulputate consequat velit viverra. Nullam ultrices laoreet lacus at tincidunt. Duis non tortor lacus. Fusce semper semper felis eget ultrices. Duis fringilla ante non nibh congue lacinia. Quisque aliquam non sapien nec fringilla.

         XOXO post-ironic pork belly, mixtape mumblecore Tumblr 8-bit wayfarers bitters 3 wolf moon tilde semiotics DIY Echo Park selfies. Wes Anderson four loko bicycle rights blog sartorial migas aesthetic banjo beard. Portland stumptown Echo Park distillery you probably haven't heard of them heirloom church-key beard, High Life meggings seitan Tumblr readymade. Authentic Godard Blue Bottle DIY, shabby chic master cleanse fanny pack meditation pug vinyl polaroid. Shoreditch 8-bit gastropub roof party kale chips crucifix, cronut four dollar toast normcore. Salvia direct trade craft beer, selvage chambray Intelligentsia YOLO keytar food truck put a bird on it kogi. Cardigan chillwave distillery Odd Future.

         It'll be booze bus also shazza got us some frog in a sock. Flat out like a bathers gutful of moolah. Mad as a ace! no dramas as busy as a give it a burl. As cross as a waggin' school piece of piss built like a chook. Come a muster piece of piss gutful of vb. He's got a massive fairy floss as dry as a spit the dummy. Mad as a wuss it'll be sheila. As stands out like kindie trent from punchy bathers. Come a gobful piece of piss shazza got us some dog's balls. Built like a bush bash when lets get some trackies.

         Pork belly corned beef ball tip bresaola picanha beef sirloin jowl venison swine pig fatback pork chop. Chicken ham tail ham hock meatball bresaola pork shankle picanha turducken brisket. Leberkas sausage swine beef ribs, pork chop porchetta sirloin boudin ribeye. Salami filet mignon jerky, cow pork loin tail chicken spare ribs doner porchetta capicola. Strip steak turducken pastrami pork loin biltong, shankle bresaola short ribs brisket drumstick spare ribs.
		)
	}

	resultString := SubStr(LoremText, p*)
	return resultString
}

